### ISSUE TITLE
 Deleting a raw-data document does not delete its report

### ISSUE THREAD

**Issue by jo** [eHealthAfrica/kazana#79]

**Comment by jo** [comment]
This should fix it: https://github.com/eHealthAfrica/kazana/pull/80

**Comment by gr2m** [comment]
I don't think that #80 will fix it. It looks more like the initial bootstrapping of data has not yet been fully implemented. What we currently do is to load all pending data reports and normalise them. 

What we don't do is to get all data report IDs from `raw-data` db, then get all data report IDs from `normalised-data` db, compare them, and if there is a data report ID in the normalised data which does not yet exist in the `raw-data`, then we can delete the indicators for it.

See the implementation for this in mNutrition here:
https://github.com/eHealthAfrica/mnutrition-normaliser/blob/develop/lib/service/bootstrap.js

The 2nd issue, and the one that @obdulia-losantos is refering to, is that deleting a data report does not get handled, and that is because the changes feed is filtered by the "pending" filter, which @jo has workaround in #80, but what I'd do is to remove the filter from the changes feed altogether, or only filter for `doc.type === 'dataReport'`. Then in the `handleDataReport` function, we should check if `doc._deleted` is true, and if it is, we should remove all its indicators. I'll make a PR on hoodie-server for discussion

**Comment by gr2m** [comment]
here is the PR: 
https://github.com/eHealthAfrica/kazana-server/issues/73
